refactored judge signatures as discussed in pull requests
scidash/sciunit pull request #174
Opened 2021-01-07 08:36 UTC by russelljjarvis

This is based on comments from the previous pull request.

2021-01-11 18:29 UTC, rgerkin requested changes
A few small changes requested.

2021-01-11 18:29 UTC, rgerkin commented on sciunit/tests.py
> +        #if config_get('PREVALIDATE', True):
I think these two lines still needs to be here (as:
```
if config_get('PREVALIDATE', False):
    self.validate_observation(self.observation)
```
What this does is run a validation step on the observation only if the `PREVALIDATE` setting in the sciunit configuration is `True`.  By default it does not exist at all, and the `False` value in that line means that it will be assumed to be `False` if it does not exist.  This means that `self.validate_observation(self.observation)` does not run unless `PREVALIDATE` is explicitly set to `True` in the configuration.  Since you removed these lines, that option is no longer available.

2021-01-11 18:29 UTC, rgerkin commented on sciunit/tests.py
> +            #if not v.validate({'observation': observation}):
I think these two lines need to stay as well (this is what does the validation of the observation, as described above).

2021-01-11 18:29 UTC, rgerkin commented on sciunit/tests.py
> +
Remove white space.

2021-01-11 21:48 UTC, russelljjarvis commented
For some reason the idea that validation is not default does not match up with my reality. It runs regardless.

2021-01-11 22:03 UTC, russelljjarvis commented
```python
from sciunit.utils import config_set
config_set('PREVALIDATE',False)
```
stdout: 
True

not sure, what this "True" means.

/home/user/git/revitalize/sciunit/sciunit
cat config.json 
{"cmap_high": 218, "cmap_low": 38}%                                                                                                                                                                                

config.json unchanged after ```config_set``` application

2021-01-12 18:34 UTC, rgerkin commented
@russelljjarvis 

The following code should work and also demonstrate the principle.
```
from sciunit.utils import config_set, config_get

config_set('PREVALIDATE', True)
assert config_get('PREVALIDATE') is True

config_set('PREVALIDATE', False)
assert config_get('PREVALIDATE') is False
```

`config_set` writes to the config.json in your home directory: `~/.sciunit/config.json`.  The other one you were looking at was probably by an old version of sciunit and is no longer read/written to (you can delete it).

Anyway, if you want pre-validation, run `config_set('PREVALIDATE', True)` and you should be set for all-time on your machine (or if in continuously re-generated environment, make sure it gets set each time you run sciunit stuff).  Or if you don't want it, use `config_set('PREVALIDATE', False)`.

2021-01-13 03:21 UTC, russelljjarvis commented
AOK, I will check it out.

2021-01-23 01:37 UTC, rgerkin reviewed
One change requested.

2021-01-23 01:37 UTC, rgerkin commented on sciunit/scores/complete.py
> +        pred = pred.rescale(obs.units)
This won't work here because there has been no check to see if the units match yet.  So if the units don't match they will get a cryptic error from this line rather than the more informative one from the assert statement below.  I think the best logic is probably to first check if base units match (i.e. seconds and milliseconds have the same base units), and then if they do not raise an exception, and if they do then rescale so they have the same units+prefix (i.e. both seconds or both milliseconds).

2021-01-23 02:48 UTC, russelljjarvis commented on sciunit/scores/complete.py
> +        pred = pred.rescale(obs.units)
As it is for TimeConstant Unit tests if prediction is in seconds, and observation is in milli seconds, then compute_score is not able to be reached.

I can rewrite the order of statements like this:
```python
        if isinstance(obs, pq.Quantity):
            assert obs.units == pred.units, \
                "Prediction must have the same units as the observation"
            assert obs.units == scale.units, \
                "RelativeDifferenceScore.Scale must have the same units as the observation"
        pred = pred.rescale(obs.units)
```
or I can leave it up to you, as I now have discussed unittesting in place that can expose these problems for you.

2021-05-03 06:45 UTC, rgerkin commented
Obsolete, I think.

2021-05-03 06:45 UTC, closed without merging