Make disk_cache persist across runs
scidash/sciunit pull request #195
Opened 2021-07-05 14:41 UTC by lakesare

2021-07-05 15:07 UTC, lakesare commented on sciunit/models/backends.py
> +            location = Path(tempfile.mkdtemp()) / "cache"
@rgerkin, as mentioned in the comment, we'll need to add `config.set_to_disk()` for the commented-out version to work.

Before I commence with that, however, how about another idea.
We can use `Path(os.getcwd()) / 'cache'`, which will create the `cache` file in the folder the user executes their script from.  
This way we don't need to mess with the config, and the user keeps direct control over the size of their cache file.  
Do you see some drawbacks to this approach?

2021-07-10 03:25 UTC, rgerkin requested changes

2021-07-16 18:59 UTC, rgerkin commented on sciunit/models/backends.py
> +        if isinstance(from_kwargs, Path) or isinstance(from_kwargs, str):
@lakesare the second argument of instance can be a tuple of types, fyi

2021-07-16 19:01 UTC, rgerkin commented on sciunit/models/backends.py
> +            location = Path(tempfile.mkdtemp()) / "cache"
Yes I prefer that, and it will persist until the user deletes.  It please do that.

2021-07-16 19:38 UTC, rgerkin requested changes
See slack and below.

2021-07-19 06:43 UTC, lakesare commented on sciunit/models/backends.py
> +            location = Path(tempfile.mkdtemp()) / "cache"
To set the record straight - we don't want `tempfile` to handle the cache location anymore (and thus we don't need to store any paths in `$HOME/.sciunit/config.json`), we want a persistent cache in `$HOME/.sciunit/cache`.
> Yes, let’s do the .sciunit location (something like $HOME/.sciunit/cache) for disk_cache=True

2021-07-19 18:05 UTC, rgerkin commented on sciunit/models/backends.py
> +            location = Path(tempfile.mkdtemp()) / "cache"
I suppose we could still allow it with some special path location argument (e.g. "_temp_") but I'm not sure what the use case would be for this, so I think you can get rid of it.

2021-07-25 04:18 UTC, rgerkin requested changes
A few changes suggested

2021-07-25 04:18 UTC, rgerkin commented on sciunit/unit_test/backend_tests.py
> +        backend.init_backend(use_disk_cache="/some/good/path", use_memory_cache=False)
Can this fake path possibly work?  Can you instead use the `tempfile` module to just explicitly create an real temporary path?  I assume that `init_backend` doesn't actually try to write to this location (so it doesn't matter if it is real or not), but in that case it isn't much of a test of whether a manual location can work.  You should instead have each of these cases actually try writing data to that cache, checking if it is there, etc.

2021-07-25 04:18 UTC, rgerkin commented on sciunit/utils.py
> +    path = Path(__file__).parent / "unit_test" / "delete_after_tests"
I think we are moving to doing everything inside HOME/.sciunit, so maybe the temp test folder should be there as well, i.e. HOME/.sciunit/unit_test.  A user could theoretically be running code from a folder in which they don't have write access, for example.

2021-07-29 13:47 UTC, lakesare commented on sciunit/utils.py
> +    path = Path(__file__).parent / "unit_test" / "delete_after_tests"
> A user could theoretically be running code from a folder in which they don't have write access, for example.

And by the user you mean the sciunit developer who runs the tests? (we only use this util for tests)

Would you prefer your temporary test files to be in `HOME/.sciunit`, somewhere outside of your git tracker?
If something bad happens and test files don't get deleted I'd certainly like to see them as my unstaged files.
If something doesn't work I'd want to uncomment the line that deletes the file, and check the file myself (without going to my HOME folder).
Do these concerns sound unrelatable?

2021-07-30 06:28 UTC, rgerkin commented on sciunit/utils.py
> +    path = Path(__file__).parent / "unit_test" / "delete_after_tests"
I think there are probably arguments both ways so I think it is fine as you have it.

2021-07-30 06:29 UTC, merged